version: '3.8'

services:
  app:
    image: aguilarufino/laravel-vue-starterkit
    container_name: laravel_app
    ports:
      - "8000:8000"
    env_file:
      - .env.prod
    depends_on:
      - mysql
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laratraining
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
