version: '3.8'

services:
  app:
    image: aguilarufino/laravel-vue-starterkit
    container_name: laravel_app
    env_file:
      - .env.prod
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    volumes:
      - app_code:/var/www-volume
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - app
    ports:
      - "8080:80"  # Or 80:80 if no reverse proxy
    volumes:
      - app_code:/var/www
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laratraining
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

volumes:
  app_code:
  db_data:

networks:
  app-network:
    driver: bridge
