# .github/workflows/docker-publish.yml

name: Build and Push Docker Image

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # - name: Log in to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to Docker Registry
        uses: docker/login-action@v2
        with:
          registry: registry.bukidnon.gov.ph
          username: ${{ secrets.PGB_REGISTRYUSERNAME }}
          password: ${{ secrets.PGB_REGISTRYPASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          pull: true
          cache-from: type=registry,ref=aguilarufino/laravel-vue-starterkit:cache
          cache-to: type=registry,ref=aguilarufino/laravel-vue-starterkit:cache,mode=max
          tags: |
            aguilarufino/laravel-vue-starterkit:latest
            aguilarufino/laravel-vue-starterkit:${{ github.sha }}
