# .github/workflows/docker-publish.yml

name: Build and Push Docker Image

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          pull: true
          platforms: linux/amd64,linux/arm64
          cache-from: type=registry,ref=aguilarufino/laravel-vue-starterkit:cache
          cache-to: type=inline
          tags: |
            aguilarufino/laravel-vue-starterkit:latest
            aguilarufino/laravel-vue-starterkit:${{ github.sha }}
